# Generated by Django 3.1.4 on 2021-11-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211112_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_status',
            field=models.CharField(choices=[('paid', 'paid'), ('notpaid', 'notpaid')], default='notpaid', max_length=30),
        ),
    ]
