# Generated by Django 3.2.2 on 2021-11-24 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_homeservicer_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='qualification',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
