# Generated by Django 3.2.6 on 2021-12-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_volunteer_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='proof'),
        ),
    ]
