# Generated by Django 3.2.6 on 2022-08-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
