# Generated by Django 3.2.6 on 2022-06-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
